### ISSUE TITLE
Forge stubbing doesn't work for non-forge forges

### ISSUE THREAD

**Issue by bodgit** [voxpupuli/beaker-module_install_helper#23]
Previously in my `spec_helper_acceptance.rb` files I would do something like this:
```ruby
proj_root = File.expand_path(File.join(File.dirname(__FILE__), '..'))
hosts.each do |host|
  puppet_module_install(:source => proj_root, :module_name => 'foo')
  on host, puppet('module', 'install', 'puppetlabs-concat'), { :acceptable_exit_codes => [0, 1] }
  ...
end
```
Then I saw the helpers in this module and figured I could just do instead:
```ruby
install_module_on(hosts)
install_module_dependencies_on(hosts)
```
Much simpler and this means there's nothing module-specific in that file anymore and it moves closer to just boilerplate.

The problem is I have no direct internet access apart from via a proxy but I do have a local Artifactory instance that is configured with a forge-like repository, the base URL of which is `http://artifactory.example.com/artifactory/api/puppet/puppet/`.

Looking at the README I figured I could just do `BEAKER_FORGE_HOST=http://artifactory.example.com/artifactory/api/puppet/puppet/ BEAKER_FORGE_API=... ...` however this doesn't work as the forge stubbing just adds an `/etc/hosts` entry for the forge hostname(s) set to the (correct) IP address of my Artifactory instance, and thereby loses the extra path in the URL, (plus it insists on using HTTPS and fails because the SSL certificate is signed by our internal CA).

I've worked around this by adding the following:
```ruby
hosts.each do |host|
  on host, puppet('config', 'set', '--section', 'main', 'module_repository', 'http://artifactory.example.com/artifactory/api/puppet/puppet')
end
```
which works however I still need to set the `BEAKER_FORGE_HOST` & `BEAKER_FORGE_API` variables due to https://github.com/puppetlabs/beaker-module_install_helper/blob/master/lib/beaker/module_install_helper.rb#L89-L104 doing a cheeky request and grabbing the list of module releases, so I'm stuck having to set the custom URL in both places.

Would it be worth making the stubbing a little more clever so it doesn't lose the URL path and scheme?

**Comment by DavidS** [comment]
cc @puppetlabs/pdk

**Comment by cdenneen** [comment]
@bodgit  what are you setting for `BEAKER_FORGE_API` here? I'd like to test this with our Artifactory

**Comment by cdenneen** [comment]
@bodgit actually I realized the API issue as you mentioned is because of the PATH getting dropped.

But I just tested as I've been using the `puppet config set` before myself and is there any benefit or need using the 2 ENV variables if you are using the module_repository setting? Think that should take care of it making the ENV variables not necessary?

**Comment by bodgit** [comment]
@cdenneen You still need to set at least one of the ENV variables (not sure which one) due to this bit of code https://github.com/puppetlabs/beaker-module_install_helper/blob/master/lib/beaker/module_install_helper.rb#L89-L104 as it goes directly to the API to retrieve the list of module releases before running `puppet module install ...` on the host, so it still needs to be configured in multiple places. (Note this bit *doesn't* drop any of the URL path, and you need to have a trailing `/` for the interpolation to work).

(Good to have someone else using Artifactory and hitting the same issues 😄)

**Comment by cdenneen** [comment]
@bodgit ah thanks... mine must be reaching out to public forge for this call. Between this and the https://github.com/voxpupuli/puppet-blacksmith/pull/66 we are on our way... much thanks for the work on this!
